name: Read Csv
on: workflow_dispatch

jobs:
   run-python:
     runs-on: ubuntu-latest

     steps:
       - uses: actions/checkout@v4

       - uses: actions/setup-python@v4
         with:
            python-version: '3.10'

       - run : pip install pandas

       - run: python python.py
       - uses : actions/upload-artifact@v4
         with:
             name: Validation report 
             path: Data/Test_Main.csv
        
       

     
   

